[payment_gateways]
# Example production EC2 instances
# 10.0.10.15 ansible_user=ubuntu
# 10.0.10.22 ansible_user=ubuntu

[web_servers]
# 10.0.20.101 ansible_user=ubuntu
# 10.0.20.102 ansible_user=ubuntu

[database_nodes]
# 10.0.30.50 ansible_user=ubuntu

[pci_scope:children]
payment_gateways
database_nodes

[local_test]
localhost ansible_connection=local ansible_python_interpreter="{{ ansible_playbook_python }}"

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
